version: '3'
services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ../administration/grafana/provisioning:/etc/shadowmute/provisioning
      - ../administration/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_ROOT_URL=http://metrics.shadowmute
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_PATHS_PROVISIONING=/etc/shadowmute/provisioning

  migration:
    image: "boxfuse/flyway:latest"
    command: "-connectRetries=10 -locations=filesystem:/migration/default/common migrate -url=jdbc:postgresql://shadowmute-pg-dev:5432/shadowmute_dev -user=shadowmute_user -password=shadowmute_pass"
    volumes:
      - ./conf/db/migration:/migration
    links:
      - shadowmute-pg-dev
    depends_on:
      - shadowmute-pg-dev

  shadowmute-pg-dev:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=shadowmute_pass
      - POSTGRES_USER=shadowmute_user
      - POSTGRES_DB=shadowmute_dev
networks:
  development:
    driver: bridge
